### ISSUE TITLE
Update copyright statement

### ISSUE THREAD

**Issue by vmbrasseur** [microsoft/oss-ssc-framework#5]
[The framework](https://github.com/microsoft/oss-ssc-framework/blob/main/specification/framework.md) includes these lines:

> ©2022 Microsoft Corporation. All rights reserved.
> 
> Licensed under [Community Specification License 1.0](https://github.com/CommunitySpecification/1.0)

These are mutually exclusive. Either all rights are reserved _or_ it's licensed under CSL-1.0.

This should be corrected anywhere it occurs in the repo, removing the errant "All rights reserved."

**Comment by camaleon2016** [comment]
> [The framework](https://github.com/microsoft/oss-ssc-framework/blob/main/specification/framework.md) includes these lines:
> 
> > ©2022 Microsoft Corporation. All rights reserved.
> > Licensed under [Community Specification License 1.0](https://github.com/CommunitySpecification/1.0)
> 
> These are mutually exclusive. Either all rights are reserved _or_ it's licensed under CSL-1.0.
> 
> This should be corrected anywhere it occurs in the repo, removing the errant "All rights reserved."

Thanks, Vicky! I believe I got all of them. Please check again to make sure we went through. I will close the issue on your thumbs up.

**Comment by ABirHAsan123-beep** [comment]
#5
