### ISSUE TITLE
Need to change definition of open source software (or use different term)

### ISSUE THREAD

**Issue by david-a-wheeler** [microsoft/oss-ssc-framework#6]
The definition of "open source software" in this document isn't a standard definition. I suggest just using a standard definition. I often use the Free Software Definition (because it's short) and then refer to the Open Source Definition for more details (because that provides more detail/clarity).

**Comment by adriandiglio** [comment]
Agreed. Will adopt short text from Free Software definition https://en.wikipedia.org/wiki/The_Free_Software_Definition, and then will link to the full definition here: https://opensource.org/osd. Will mark it closed once change has been made in the Markdown.
