### ISSUE TITLE
How does this relate to SCITT?

### ISSUE THREAD

**Issue by kimsterv** [microsoft/oss-ssc-framework#7]
How does oss-ssc compare/contrast with SCITT (https://github.com/ietf-scitt) the other supply chain framework Microsoft is helping to drive?

**Comment by adriandiglio** [comment]
The way that this relates to SCITT is that if a team/organization adopted the OSS SSC Framework requirements, they could potentially output "attestations of conformance" to the OSS SSC Framework requirement and store it in SCITT. We will take an action to explain this relationship in the document/appendix.
