### ISSUE TITLE
Make it clear projects don't all have to be at the top level

### ISSUE THREAD

**Issue by david-a-wheeler** [microsoft/oss-ssc-framework#9]
Proposal: Ensure that it’s clear that not all projects will want to be the top level & you may want a mix of levels (e.g., level 2 for some criteria, 3 for others). Potentially add more clarification around Level 4 being aspirational in most cases

**Comment by adriandiglio** [comment]
Acknowledged. We will take an action to make this more clear about Maturity Level 4 being largely aspirational.
